spring:
  application:
    name: 2026_Silver_Residence


  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen3.5:9b

  data:
    mongodb:
      host: localhost
      database: Silver
      port: 27017