spring:
  application:
    name: 2026_Silver_Residence


  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen3.5:9b
        options:
          temperature: 0.1
#          上下文最大数
          num-ctx: 2048
#          最大token数
          num-predict: 512
#          重复惩罚
          repeat-penalty: 1.1
      init:
        timeout: 30s

  data:
    mongodb:
      host: localhost
      database: Silver
      port: 27017